#!/usr/bin/env bash
# Pandey - UserBot
# Copyright (C) 2021-2023 TeamPandey
#
# This file is a part of < https://github.com/TeamPandey/Pandey/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/TeamPandey/Pandey/blob/main/LICENSE/>.

bash resources/session/session.sh
