blank_issues_enabled: true
contact_links:
  - name: Pandey Support
    url: https://t.me/PandeySupportChat
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://ultroid.tech/
    about: Basic documentation for setting up.
